stages: [test, image]

default:
  image: maven:3.9.9-eclipse-temurin-21
  cache:
    key: maven
    paths:
      - .m2/repository

maven:test:
  stage: test
  before_script:
    - chmod +x mvnw
  script:
    - ./mvnw -B -ntp test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH
    - if: $CI_COMMIT_TAG
  artifacts:
    when: always
    reports:
      junit: "**/target/surefire-reports/*.xml"

# image:build-no-push:
#   stage: image
#   rules:
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   before_script:
#     - chmod +x mvnw
#   script:
#     - >
#       ./mvnw -B -ntp spring-boot:build-image
#       -DskipTests
#       -Dspring-boot.build-image.publish=false
#       -Dspring-boot.build-image.imageName="$CI_REGISTRY_IMAGE:main-check"

image:release-push:
  stage: image
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - chmod +x mvnw
  script:
    - >
      ./mvnw -B -ntp spring-boot:build-image
      -DskipTests
      -Dspring-boot.build-image.builder=paketobuildpacks/builder-jammy-full
      -Dspring-boot.build-image.publish=true
      -Dspring-boot.build-image.imageName="$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG"
      -Ddocker.publishRegistry.url="$CI_REGISTRY"
      -Ddocker.publishRegistry.username="$CI_REGISTRY_USER"
      -Ddocker.publishRegistry.password="$CI_REGISTRY_PASSWORD"
      -Dspring-boot.build-image.env.JAVA_TOOL_OPTIONS="-Dio.netty.native.workdir=/workspace"
      -Dio.netty.native.workdir=/workspace